[toolchain]
anchor_version = "0.29.0"

[features]
seeds = true
resolution = true

[programs.devnet]
stps = "FuAM2peBxYQgr4Sspd43FkYK7vuCZ5rTPxZYCnCSeCZk"

[programs.localnet]
stps = "FuAM2peBxYQgr4Sspd43FkYK7vuCZ5rTPxZYCnCSeCZk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./scripts/test-anchor.sh"
